mappings:
  GoogleGeocoding: Symbiote\Addressable\GoogleGeocoding
  Addressable: Symbiote\Addressable\Addressable
  Geocodable: Symbiote\Addressable\Geocodable
  RegexTextField: Symbiote\Addressable\RegexTextField
  GeocodableTest: Symbiote\Addressable\Tests\GeocodableTest
  AddressableDataObjectTest: Symbiote\Addressable\Tests\AddressableDataObjectTest
  GeocodableDataObjectTest: Symbiote\Addressable\Tests\GeocodableDataObjectTest
  AddressableTest: Symbiote\Addressable\Tests\AddressableTest
